--- @class StaticPopupDialog : Frame
--- @field text FontString The dialog message text
--- @field button1 Button The first action button (e.g. ADD/YES)
--- @field button2 Button The second action button (e.g. CANCEL/NO)
--- @field button3 Button The optional third action button
--- @field EditBox EditBox The input field (when hasEditBox = 1)
--- @field icon Texture The dialog icon texture
--- @field checkButton CheckButton The optional checkbox (when hasCheckButton = 1)
--
--

--- Shows a static popup dialog defined in StaticPopupDialogs.
---
--- @param which string                      -- Key of StaticPopupDialogs entry
--- @param text_arg1 string|number           -- Replaces %s in dialog.text (first)
--- @param text_arg2 string|number           -- Replaces %s in dialog.text (second)
--- @param data any                          -- Passed to OnAccept / OnCancel handlers
--- @param insertedFrame FrameObj            -- Optional frame inserted into dialog
--- @param insertedFrameData any             -- Data for inserted frame
--- @return  FrameObj 		                   -- The created popup frame (if shown)
function StaticPopup_Show(which, text_arg1, text_arg2, data, insertedFrame, insertedFrameData) end
